### ISSUE TITLE
Could lib/tasks/migrate.rake be renamed to something more unique?

### ISSUE THREAD

**Issue by vergenzt** [instructure/outrigger#1]
I'm using this library in conjunction with [ctran/annotate_models](https://github.com/ctran/annotate_models), and both libraries add a file to the Ruby load path called "lib/tasks/migrate.rake".

The Railtie for outrigger calls `load "lib/tasks/migrate.rake"`, but because annotate_models happens to appear first in my `$LOAD_PATH`, only its `migrate.rake` gets loaded.

Could the Rake file be renamed to something involving this gem's name to avoid the conflict?

**Comment by vergenzt** [comment]
(I've filed this same issue with annotate_models at ctran/annotate_models#468.)

**Comment by simonista** [comment]
Fixed in 555dfffd2bebb007e456cd369b54c1c618c8d398
