### ISSUE TITLE
add_offense not supported for rubocop > 0.51.0

### ISSUE THREAD

**Issue by ryanbjones** [instructure/outrigger#5]
Using Rails 5 and rubocop 0.52.1 you'll get a wrong number of arguments error. Not sure the best way to support both ways of this, but either the gemspec should specify that constraint or the gem should be updated to support it

https://github.com/bbatsov/rubocop/blob/v0.52.0/lib/rubocop/cop/cop.rb#L119

**Comment by maths22** [comment]
Cleaning up old issues; this was corrected years ago.
