### ISSUE TITLE
Support Rails 6

### ISSUE THREAD

**Issue by arich** [instructure/outrigger#8]
Hello! Can we get Rails 6 support added? Currently the Gemspec prevents using this gem in Rails 6 applications. Thanks!

**Comment by simonista** [comment]
Yes! Let me look into that, thanks for bringing it up.

**Comment by simonista** [comment]
Fixed in df8f19800a46bda707958243ae1d7b56b8708fdf and 2.1.0 released. Unit tests pass, but I haven't done any further testing yet. Please let me know if you run into any issues.
